name: CI on main

on:
  push:
    branches:
      - main
      
permissions:
  checks: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Debug

      - name: Run tests
        run: dotnet test ./tests/TestFabric.Test/TestFabric.Test.csproj --no-build --configuration Debug --verbosity normal --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults/TestFabric

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults/

      - name: Publish test summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: TestFabric Tests
          path: ./TestResults/TestFabric/test_results.trx
          reporter: dotnet-trx
